# Generated by Django 2.0.7 on 2018-07-31 01:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.TextField()),
                ('init_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
