# Generated by Django 2.1.1 on 2018-10-23 03:34

import brews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brews', '0002_auto_20181023_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='category',
            field=models.CharField(choices=[(brews.models.Category(0), 0), (brews.models.Category(1), 1), (brews.models.Category(2), 2), (brews.models.Category(3), 3)], default=brews.models.Category(3), max_length=1),
        ),
    ]
